DEBUG = True
WIDTH = 256
HEIGHT = 256
CAPTION = "Mario Bros"
FPS = 30
CANVAS_DISPLAY_SCALE = 3
GAME_RESOURCES = "assets/sprites-ssg-lpr.pyxres"
SPRITE_SPEED_X = 2
SPRITE_JUMP_INITIAL_SPEED = 8
GRAVITY = 0.5
MARIO_LIVES = 3
GAME_OVER_DELAY = 3 # seconds

PLAYING_AREA_START_X = 0
PLAYING_AREA_START_Y = 56

TILEMAP_START_X = 0
TILEMAP_START_Y = 64

BIGENTITY_DEATH_SCORE = 100
BIGENTITY_UPSIDE_SCORE = 50
COIN_SCORE = 25